import { test, expect } from '@playwright/test';

test('ErvaringsdeskundigeRegistratie', async ( {page}) => {

    await page.goto('https://wpr23-24b.azurewebsites.net/');
await page.getByRole('link', { name: 'Inloggen' }).click();
await page.getByLabel('Registreer u hier').click();
await page.getByText('Registreer jezelf als').click();
await page.locator('label').filter({ hasText: 'Nee' }).getByRole('radio').check();
await page.getByPlaceholder('Vul hier je volledige naam in').click();
await page.getByPlaceholder('Vul hier je volledige naam in').fill('TestGebruiker1');
await page.getByPlaceholder('Vul hier je volledige naam in').press('Tab');
await page.getByPlaceholder('Vul hier je email-adres in').fill('testgebruiker1@example.com');
await page.getByPlaceholder('Vul hier je email-adres in').press('Tab');
await page.getByPlaceholder('Vul hier je wachtwoord in').fill('Testgebruiker');
await page.getByPlaceholder('Vul hier je wachtwoord in').press('Control+a');
await page.getByPlaceholder('Vul hier je wachtwoord in').fill('Testgebruiker1/');
await page.getByPlaceholder('Vul hier je wachtwoord in').press('Tab');
await page.getByPlaceholder('Vul hier je wachtwoord opnieuw in').fill('Testgebruiker1/');
await page.getByPlaceholder('Vul hier je wachtwoord opnieuw in').press('Tab');
await page.getByPlaceholder('Vul hier je postcode in').fill('2121AB');
await page.getByPlaceholder('Vul hier je postcode in').press('Tab');
await page.getByPlaceholder('Vul hier uw geboortedatum in').click();
await page.getByPlaceholder('Vul hier uw geboortedatum in').fill('2024-01-19');
await page.getByPlaceholder('Vul hier je telefoonnummer in').click();
await page.getByPlaceholder('Vul hier je telefoonnummer in').fill('0612345678');
await page.getByLabel('Volgende pagina').click();
await page.locator('#fysiekeBeperkingCheckbox').check();
await page.locator('#visueleBeperkingCheckbox').check();
await page.locator('#auditieveBeperkingCheckbox').check();
await page.getByLabel('Volgende pagina').click();
await page.getByLabel('Sta commerciële benaderingen').check();
await page.locator('#BenaderingPortal').check();
await page.getByLabel('Sta telefonische benaderingen').check();
await page.getByLabel('Afronden Registratie').click();
});


test('ErvaringsdeskundigeRegistratieMetOngeldigePersoonsGegevens', async ( {page}) => {
await page.goto('https://wpr23-24b.azurewebsites.net/');
await page.getByRole('link', { name: 'Inloggen' }).click();
await page.getByLabel('Registreer u hier').click();
await page.getByText('Registreer jezelf als').click();
await page.getByPlaceholder('Vul hier je volledige naam in').click();
await page.getByText('Nee').click();
await page.getByPlaceholder('Vul hier je volledige naam in').click();
await page.getByPlaceholder('Vul hier je volledige naam in').fill('Hallo');
await page.getByPlaceholder('Vul hier je volledige naam in').press('Control+a');
await page.getByPlaceholder('Vul hier je volledige naam in').fill('TestGebruiker2');
await page.getByPlaceholder('Vul hier je volledige naam in').press('Tab');
await page.getByPlaceholder('Vul hier je email-adres in').fill('testgebruiker');
await page.getByPlaceholder('Vul hier je email-adres in').press('Tab');
await page.getByPlaceholder('Vul hier je wachtwoord in').fill('testgebruiker');
await page.getByPlaceholder('Vul hier je wachtwoord in').press('Tab');
await page.getByPlaceholder('Vul hier je wachtwoord opnieuw in').fill('testgebruiker');
await page.getByPlaceholder('Vul hier je wachtwoord opnieuw in').press('Tab');
await page.getByPlaceholder('Vul hier je postcode in').fill('2834');
await page.getByPlaceholder('Vul hier je postcode in').press('Tab');
await page.getByPlaceholder('Vul hier uw geboortedatum in').click();
await page.getByPlaceholder('Vul hier uw geboortedatum in').fill('2024-01-04');
await page.getByPlaceholder('Vul hier je telefoonnummer in').click();
await page.getByPlaceholder('Vul hier je telefoonnummer in').fill('06');
await page.getByLabel('Volgende pagina').click();
await page.getByPlaceholder('Vul hier je email-adres in').click();
await page.getByPlaceholder('Vul hier je email-adres in').fill('testgebruiker2@example.com');
await page.getByPlaceholder('Vul hier je wachtwoord in').click();
await page.getByPlaceholder('Vul hier je wachtwoord in').click();
await page.getByPlaceholder('Vul hier je wachtwoord in').click();
await page.getByPlaceholder('Vul hier je wachtwoord in').press('Control+a');
await page.getByPlaceholder('Vul hier je wachtwoord in').fill('Testgebruiker2!');
await page.getByPlaceholder('Vul hier je wachtwoord in').press('Tab');
await page.getByPlaceholder('Vul hier je wachtwoord opnieuw in').fill('Testgebruiker2!');
await page.getByPlaceholder('Vul hier je postcode in').click();
await page.getByPlaceholder('Vul hier je postcode in').fill('2834AB');
await page.getByPlaceholder('Vul hier je telefoonnummer in').click();
await page.getByPlaceholder('Vul hier je telefoonnummer in').fill('0612345679');
await page.getByLabel('Volgende pagina').click();
await page.getByText('Nee').click();
await page.locator('label').filter({ hasText: 'Nee' }).getByRole('radio').check();
await page.getByLabel('Volgende pagina').click();
await page.locator('#auditieveBeperkingCheckbox').check();
await page.locator('#visueleBeperkingCheckbox').check();
await page.locator('#fysiekeBeperkingCheckbox').check();
await page.getByLabel('Anders, namelijk..').selectOption('mobility');
await page.getByLabel('Volgende pagina').click();
await page.getByText('Sta telefonische benaderingen').click();
await page.getByText('Sta benadering via portaal toe').click();
await page.getByText('Sta commerciële benaderingen').click();
await page.getByText('Sta benadering via portaal toe').click();
await page.getByText('Sta benadering via portaal toe').click();
await page.locator('#BenaderingPortal').check();
await page.getByLabel('Afronden Registratie').click();
});


test('ErvaringsdeskundigeRegistratieMetOngeldigeBeperkingEnBenaderingInvoer', async ( {page}) => {
await page.goto('https://wpr23-24b.azurewebsites.net/');
await page.getByRole('link', { name: 'Inloggen' }).click();
await page.getByLabel('Registreer u hier').click();
await page.getByText('Registreer jezelf als').click();
await page.locator('label').filter({ hasText: 'Nee' }).getByRole('radio').check();
await page.getByPlaceholder('Vul hier je volledige naam in').click();
await page.getByPlaceholder('Vul hier je volledige naam in').fill('Testgebruiker3');
await page.getByPlaceholder('Vul hier je volledige naam in').press('Tab');
await page.getByPlaceholder('Vul hier je email-adres in').fill('testgebruiker3@example.com');
await page.getByPlaceholder('Vul hier je email-adres in').press('Tab');
await page.getByPlaceholder('Vul hier je wachtwoord in').fill('Testgebruiker3!');
await page.getByPlaceholder('Vul hier je wachtwoord in').press('Tab');
await page.getByPlaceholder('Vul hier je wachtwoord opnieuw in').fill('testgebruiker3@ec');
await page.getByPlaceholder('Vul hier je wachtwoord opnieuw in').press('Control+a');
await page.getByPlaceholder('Vul hier je wachtwoord opnieuw in').fill('Testgebruiker3!');
await page.getByPlaceholder('Vul hier je wachtwoord opnieuw in').press('Tab');
await page.getByPlaceholder('Vul hier je postcode in').fill('2121BC');
await page.getByPlaceholder('Vul hier je postcode in').press('Tab');
await page.getByPlaceholder('Vul hier uw geboortedatum in').click();
await page.getByPlaceholder('Vul hier uw geboortedatum in').fill('2024-01-05');
await page.getByPlaceholder('Vul hier je telefoonnummer in').click();
await page.getByPlaceholder('Vul hier je telefoonnummer in').fill('0612345675');
await page.getByLabel('Volgende pagina').click();
await page.getByLabel('Volgende pagina').click();
await page.locator('#auditieveBeperkingCheckbox').check();
await page.getByLabel('Volgende pagina').click();
await page.getByLabel('Afronden Registratie').click();
await page.getByLabel('Sta telefonische benaderingen').check();
});